vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    poster_file:
      # alias qui nous permet d'accéder à nos images depuis le navigateur
      uri_prefix: /uploads/images/posters
      upload_destination: "%upload_directory%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    photos_file:
      # alias qui nous permet d'accéder à nos images depuis le navigateur
      uri_prefix: /uploads/images/photos
      upload_destination: "%upload_directoryForActors%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
